---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-slinky-slurm-net-v1beta1-nodeset
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: nodeset-mutate-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate--v1-binding
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: podsbinding-v1.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods/binding
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1beta1-accounting
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: accounting-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accountings
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1beta1-controller
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: controller-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - controllers
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1beta1-loginset
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: loginset-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - loginsets
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1beta1-nodeset
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: nodeset-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodesets
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1beta1-restapi
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: restapi-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - restapis
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1beta1-token
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: token-v1beta1.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tokens
  sideEffects: None
